package enums;

public enum Buff {
	PHYSICAL_DAMAGE,
	FIRE_ATTACK, ICE_ATTACK, LIGHTNING_ATTACK, DARKNESS_ATTACK,
	SOLAR_ATTACK, LUNAR_ATTACK, PHOTON_ATTACK, GRAVITON_ATTACK,
	NON_ELEMENTAL_ATTACK,
	
	ANTI_PHYSICAL, ANTI_NON_ELEMENTAL,
	ANTI_FIRE, ANTI_ICE, ANTI_LIGHTNING, ANTI_DARKNESS,
	ANTI_SOLAR, ANTI_LUNAR, ANTI_PHOTON, ANTI_GRAVITON,
	
	BARRIER,
	AUGMENT_CIRCLE, NEGATE_CIRCLE
	
}
